### ISSUE TITLE
Bounce.h missing

### ISSUE THREAD

**Issue by dpage001** [grapefrukt/kitchen-timer#1]
I love the project, so I'm working on it myself - except that I had an Arduino Pro Mini to use as the microcontroller. Maybe that is part of my problem. However, upon loading and compiling the kitchen-timer.ino project file in the Arduino IDE, Bounce.h as referenced by a #include is not found. Is that missing from the code package, or is it a result of me using a different microcontroller?

There are then two follow-on issues. There are variables declared of type elapsedMillis - I had to change those to "longs" to get it to compile. Finally, what pin is the piezo speaker defined on? Mine is silent...

**Comment by grapefrukt** [comment]
The [bounce library I use comes with Teensyduino](https://www.pjrc.com/teensy/td_libs_Bounce.html). It's the precursor to [Bounce2](https://github.com/thomasfredericks/Bounce2), which I really should have used, I just forgot. Swapping it out should be very straightforward. There's even [migration instructions here](https://playground.arduino.cc/Code/Bounce/). 

[elapsedMillis is again a library that comes with Teensyduino](https://github.com/pfeerick/elapsedMillis), you should be able to drop this in your project and go. You can read/write them as if they were regular variables, but there's special trickery in the background to increment those counters with each millisecond that passes. 

The pins used for [the piezo is defined here, in toneAC.h](https://github.com/grapefrukt/kitchen-timer/blob/a57f52cfc5fc2733b17f7659a656574868cb08a4/toneAC.h#L37)
It uses two pins to drive the piezo "differentially", one is set low the other high in an alternating fashion for extra volume. It may be possible to use different pins here, the defaults happened to fit my use case so I never looked into it. 

It's very exciting that you're building your own, looking forward to see your progress!

**Comment by dpage001** [comment]
Thanks for the guidance - clearly this "issue" was the result of me building mine with a different board.

**Comment by dpage001** [comment]
Martin,

After connecting the piezo to the correct pins, and installing Bounce2 (all
I had to do was use the new constructor and initialization code) and
including elapsedMillis.h, it works perfectly! Now I just have to solder it
together and make an enclosure.

A question: what is the use of the clickable button in the rotary? As far
as I can tell, the only thing it can do is silence the chirp after the
timer goes to zero. Is it supposed to have a use other than that?

Thanks,

Dennis

**Comment by grapefrukt** [comment]
Great that you got it working!

The button is only used for silencing the alarm (which can be done by rotating too) and if you hold it for a second or two it will reset the timer to zero.

For me, the silencing (with button) isn't working correctly at the moment, i haven't had time to look into it, but it did work before so i likely broke something in the code.

**Comment by dpage001** [comment]
A couple more questions:
- I see you have a PIN_SLEEP_LED defined for pin 6. I don't think your
video shows what happens when the timer goes to sleep, but is this just an
led to turn on when the timer goes to sleep? I don't see this connection in
your fritzing diagram...
- My charger has a bright blue led when it has power. It looks like your
video shows no blue power led. Did you do something to disable yours?
- The video includes the music played when the timer goes to zero. It has
multiple tones in a little jingle. Mine only plays a single-tone chirp
every second or so, despite being connected to pins 9 and 10 for the Atmega
328. Any ideas?

Thanks again!

**Comment by grapefrukt** [comment]
I used the built in LED on the Teensy to debug the sleep mode, there's another define `USE_SLEEP_LED ` that toggles the use of that. I have no idea how the sleep will work on anything that's not a Teensy 2.0, so you're on your own there 😉

Assuming you're using the Powerboost 500, you can desolder that LED. [I even asked on the Adafruit forums and got a confirmation it'd work beforehand](https://forums.adafruit.com/viewtopic.php?f=19&t=182093). I kept the charge and low-battery ones. 

I'm not sure what could make the "music" playback behave like that, everything related to the "music" playback lives in [music.cpp](https://github.com/grapefrukt/kitchen-timer/blob/main/music.cpp) with the tones defined in [music_data.h](https://github.com/grapefrukt/kitchen-timer/blob/main/music_data.h). But, I kept a few of my test songs in there. You could potentially try and replace one of the `playMelody()` calls in the main file with say, `playMelody(melody_nevergonnagive)` and maybe that'll make it easier to tell what's going on. Likely it's messing up on the wait between tones somehow.

**Comment by dpage001** [comment]
Oh no! After soldering most of my project together on a board, I found that my display is upside down! :( Is there an easy way for me to "rotate" the display through code? Or do I need to get the unsoldering ribbon out?

**Comment by grapefrukt** [comment]
Oh no!
Since the display uses adafruits gfx library you should be able to use this:
https://learn.adafruit.com/adafruit-gfx-graphics-library/rotating-the-display

**Comment by dpage001** [comment]
Thanks for your help, Martin! I tried to send some photos of my final
build, but they were too large for github....

**Comment by grapefrukt** [comment]
I'd love to see them! You can email me directly at m@grapefrukt.com
